### PR TITLE
Add ncsa and varnish logs with logrotate.d configuration.

### PR DESCRIPTION
**Pull request by shmuel-krakower**
Based on gagor pull request (https://github.com/gagor/varnish/commit/0a9969f2854fe6fedfe785e56226682d20008a1e)

Please note that I've changed the default varnish log to false (not log) as this log is mostly for tracing.
Instead, I've enabled by default the ncsa log with the original varnish format.

I've also add log rotation policy which may be configured now from this cookbook.

### CODE REVIEW

**Comment by prometheanfire** [comment]
what if logrotate is not installed?

**Comment by shmuel-krakower** [comment]
@prometheanfire - fixed it to only configure logrotate.d if it is available.

**Comment by ramereth** [comment]
I think this looks better however when I try to run it in test kitchen varnishncsa doesn't seem to be running. This is strange because I can see it starting in the chef output, but when I check the ps output I don't see it.

Can any of you confirm the same on your end?

**Comment by ramereth** [comment]
It might be helpful if you add some serverspec tests to verify it as well. Thanks for the PR based on my feedback!

**Comment by gagor** [comment]
Thanks @shmuel-krakower for merging this. I have done this exactly same way in my wrapper cookbook.

**Pull request closed without merging**
