### PR TITLE
Rewrite

### PR DESCRIPTION
**Pull request by RyanJarv**
Will probably need to add a section on upgrading to this version but let me know if you have any thoughts or suggestions on any of this.

Thanks!

### CODE REVIEW

**Comment by RyanJarv** [comment]
Tagging #113

**Comment by martinb3** [comment]
Hi @RyanJarv! 

I just cloned this down and took it for a spin. It looks like there's an issue with the `varnish41-ubuntu-1404` test:

```
       Failures:

         1) Command "curl localhost:6081" exits zero
            Failure/Error: expect(subject.exit_status).to eq 0

              expected: 0
                   got: 127

              (compared using ==)
              env PATH="/sbin:/usr/sbin:/bin:/usr/bin" /bin/sh -c curl\ localhost:6081
```

**Comment by RyanJarv** [comment]
Hm.. I'm not getting that error, How you're running the tests and what is the output of that curl command?

I guess my last commit adding comments to the varnishlog init script did break varnish3-ubuntu-1404 though so will have to fix that as well.

**Comment by martinb3** [comment]
Yeah -- ended up with:

```
>>>>>>     Converge failed on instance <varnish3-ubuntu-1404>.  Please see .kitchen/logs/varnish3-ubuntu-1404.log for more details
>>>>>>     Converge failed on instance <varnish3-ubuntu-1204>.  Please see .kitchen/logs/varnish3-ubuntu-1204.log for more details
>>>>>>     Verify failed on instance <varnish4-ubuntu-1404>.  Please see .kitchen/logs/varnish4-ubuntu-1404.log for more details
>>>>>>     Verify failed on instance <varnish41-ubuntu-1404>.  Please see .kitchen/logs/varnish41-ubuntu-1404.log for more details
```

It looks like, for Ubuntu, curl simply isn't installed. Once I do that, the tests all pass. I will note that:
```
       Command "curl localhost:6081"
         exits zero
```

However:
```
root@varnish41-ubuntu-1404:~# curl localhost:6081 -I
HTTP/1.1 503 Backend fetch failed
```

**Comment by RyanJarv** [comment]
Ah ok, curious how old your vagrant box is and if updating it fixes it. Thinking it might be better to leave out the curl install out if it's just caused by an old ubuntu version (assuming the change wasn't too recent at least). The 503 is because there isn't actually a backend configured in the tests but I think that would be good to add along with maybe some varnishtest cases.

Added the fixes for the varnish3-ubuntu-1404 thing and will probably have some time next week to add some notes on upgrading and get a test w/ nginx running. Other then that I think it should be good for a non-published version.

**Comment by martinb3** [comment]
Updating vagrant boxes, plus pulling your additional commits, seems to fix the remaining failures 👍

**Comment by RyanJarv** [comment]
Ok awesome. So did a bit of looking around and it looks like wget is installed by default on the earlier ubuntu images and from what I'm reading it's more commonly available by default, anyways probably doesn't matter much either way. Thanks for getting this merged! I'm assuming the permission denied error is something on the CircleCi side of things but let me know if need to do anything there.

**Pull request merged**
