### PR TITLE
Issue #62

### PR DESCRIPTION
**Pull request by tgagor**
This should help with issue #62

My pull request will fill varnish.params with proper values based on older sysconfig/varnish file. It's not full problem resolution (still nfiles and memlock will require to overwrite systemd config file) but it's getting closer.

There is also older part that will enable varnishncsa instead varnishlog (I remember it was done in 1.1 version..).

### CODE REVIEW

**Comment by prometheanfire** [comment]
I think I'm fine with merging this, even though we are moving everything to the library methods.  Can you test cent7 with the libraries?  It was working last I checked.

**Comment by prometheanfire** [comment]
reload of varnish failed for varnish4-ubuntu-1404

    883 I, [2015-03-31T11:45:11.409883 #7288]  INFO -- varnish4-ubuntu-1404:     ---- Begin output of /etc/init.d/varnish reload ----
    884 I, [2015-03-31T11:45:11.410085 #7288]  INFO -- varnish4-ubuntu-1404:     STDOUT: * Reloading HTTP accelerator varnishd
    885 I, [2015-03-31T11:45:11.410315 #7288]  INFO -- varnish4-ubuntu-1404: ...fail!

**Comment by gagor** [comment]
I will check this tomorrow

wt., 31 mar 2015, 19:29 Matthew Thode użytkownik <notifications@github.com>
napisał:

**Comment by gagor** [comment]
This doesn't look like my fault :-)
It's rather case with Ubuntu's init script or how it's reloading varnish configuration.

**Comment by prometheanfire** [comment]
Heh, fair enough.  How did using the libraries instead go?  We are likely to move to them (only) fairly soon.

**Comment by gagor** [comment]
For me libraries are harder to interpret when you're trying to understand cookbooks written by others. Especially when not everything is working as expected.

In case of this cookbook it's working quite well by default and this is enough for me. But it's not working as expected with systemd and in case of logging.

Is there a chance that my pull request will be merged soon?

**Comment by mattjbarlow** [comment]
@gagor Sorry for the delay. The Ubuntu restart issue was resolved today. I'm reviewing this PR and it is duplicating functionality that already exists in the libraries. The libraries already support CentOS 7 and varnishncsa logging.


Another advantage of the libraries are that they are fully tested with both ChefSpec and Serverspec. You can find some examples of using them [https://github.com/rackspace-cookbooks/varnish/tree/master/test/fixtures/cookbooks/install_varnish/recipes](here).

I'm more than happy to discuss on IRC (mattjbarlow on freenode) or through another method. Let me know your thoughts. Also, I'm happy to help with any challenges you face with the libraries.

**Comment by gagor** [comment]
Hi @mattjbarlow,
I was involved in other projects and didn't have time earlier to review those libraries, today I have it. 

First I have to say that I respect your work but I'm sceptical about way these libraries and I will explain in details why:

1. All these libraries were NOT written to be used multiple times like any other classical LWRP (ex. directory, package). These libraries are just encapsulated recipes.

2. varnish_install - this library will install package varnish just like package! It's useless for me. If you want to say that it manages repo too this may be done ex. like:
```
include_recipe "#{coobook_name}::configure_repo_stuff_to_get_out_of_users_eyes"
package 'varnish' do
  version 4.0.3
end
```
Nothing more is needed.

3. varnish_default_vcl - this library might be interesting if you add ability to search for backends via roles, etc. But for now it's just template call but written in less readable way.

4. varnish_default_config - this one was looking promising and usable... but at the end it turned out that it's not. One reason - it doesn't use default attributes set in cookbook, so to use it I have to call it with all parameters (plus probably some conditionals) referencing node attributes.

If you have to go this way you should use these libraries in default recipe and make use of attributes, because for now it's just simpler for me to use older version of cookbook and apply wrappers to get it working like expected.

**Comment by martinb3** [comment]
@gagor, many, many community cookbooks are being rewritten to library cookbooks. It's definitely the trend in the community, as far as I can see from recent releases as well as from the community summits and Chef Conf. Recent rewrite examples include [mysql](https://github.com/chef-cookbooks/mysql), [httpd](https://github.com/chef-cookbooks/httpd), [database](https://github.com/opscode-cookbooks/database), [yum](https://github.com/chef-cookbooks/yum/tree/master/recipes), [git](https://github.com/jssjr/git). I think the goal with this cookbook is eventually to make it reusable multiple times, like you describe for other resources like package and directory. 

My sense of this trend towards libraries is that it's driven because it's much easier to extend small, self-contained building blocks like install/configure/service resources, than it is to adjust attributes to make an upstream recipe behave differently. I feel that it is very difficult to adjust a recipe's behavior if it doesn't provide an attribute, and attributes tend to proliferate and become tricky to maintain when there are sufficiently many of them.

**Comment by gagor** [comment]
Thanks for response @martinb3. I use those cookbooks but they switched to libraries because of reason. I love how I may easily enable/disable apache modules/vhosts etc. But here you switched to libraries because it's trendy (I'm really sad to tell that).
I think that libraries for managing backends, probes or maybe installing vmods may have sense. Current libs IMHO are just rewritten chef DSL to pure Ruby not because it will be more usable but trendy ;-/
I'm not lib hater - but I just can't see sense for such step in this cookbook.

P.S. Unit testing is not a reason or additional value of lib - I'm testing classic chef DSL without problems :)

**Comment by martinb3** [comment]
> But here you switched to libraries because it's trendy (I'm really sad to tell that).

I tried to explain why I think there's a trend towards libraries in my previous comment, and why I think it's a better design in the second paragraph of my comment. We hope to iterate over time to remove some of the pure recipe-DSL and attribute usage in favor of pure ruby. I believe that resources and providers offer more flexibility to the user, and make it easier to maintain the logic.

I think we would be willing to merge PRs that add functionality to the providers _and_ exposes the corresponding resources to the cookbook as a recipe with attributes. I feel like this is a reasonable compromise, as it would allow those who prefer using recipes and attributes to make use of them, and those who prefer declaring resources to make use of those. Would you agree?

**Comment by mattjbarlow** [comment]
There were a number of long standing issues such as lack of ncsa logging support and systemd / centos 7 support. When implementing these fixes, we decided to switch to libraries in order to be more composeable and declarative in end user recipes. Composeable because, with libraries, if you want to install Varnish but not lay down a default template, you can use only the `install_varnish` resource. Declarative because it is easy to see in your cookbook exactly how resources are configured without having to backtrack through included cookbooks.

Granted there are other ways to accomplish these things. I agree with @martinb3. This PR is for CentOS 7 support, which already exists in the libraries. If we could rewrite the existing recipes to use the working libraries for CentOS 7, and the existing node attributes, would that be acceptable?

**Comment by gagor** [comment]
I think we should leave topic of libraries - we are free people and we do not have to agree on that :-)

Summing up, if you have working libraries, please use them (like in provided examples). Use current attributes schema (if possible) to configure it and get all benefits of those new libraries. I do not want anything more :-)

**Comment by martinb3** [comment]
I think, since we're moving to LWRPs, we don't need this change anymore. Thank you to all who contributed!

**Pull request closed without merging**
